version: '3.8'

services:
  app:
    image: alimism/rsu_reciclaje_app:v1.0
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network

  webserver:
    image: alimism/rsu_reciclaje_nginx:v1.0
    container_name: nginx_webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  mysql:
    image: alimism/rsu_reciclaje_mysql:v1.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rsu_reciclaje
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
